### ISSUE TITLE
webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.

### ISSUE THREAD

**Issue by jinwei14** [mauris/lps-demo-web#1]
Hi sam I am the Master student in imperial who is going to continue your work in the js visualisation bit. I had a lot of problem in running your demo web application. Here are the errors that I met. Will you please help me ?
<img width="819" alt="Screenshot 2019-04-18 at 16 36 16" src="https://user-images.githubusercontent.com/26280459/56373323-991b5600-61f8-11e9-8b53-8cdf5d9340f8.png">
<img width="806" alt="Screenshot 2019-04-18 at 16 36 26" src="https://user-images.githubusercontent.com/26280459/56373327-9ae51980-61f8-11e9-9da6-17388c48646d.png">

**Comment by mauris** [comment]
@jinwei14 thanks for reaching out. I must admit it's been one year already and I need a refresher on Angular/Webpack. Some dependencies might have been deprecated during the time I'm away from this implementation.

Is it possible for you to copy-paste the following:

1) command you were trying to run
2) complete output of the executed command

Thanks!

**Comment by jinwei14** [comment]
```shell
(base) jinweizhang@dyn3173-185:~/Desktop/Project/try/lps-demo-web$ nvm list
         v6.0.0
        v8.11.3
->     v10.15.3
         system
default -> 8.11.3 (-> v8.11.3)
node -> stable (-> v10.15.3) (default)
stable -> 10.15 (-> v10.15.3) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> v10.15.3)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.15.3
(base) jinweizhang@dyn3173-185:~/Desktop/Project/try/lps-demo-web$ npm i

> fsevents@1.2.4 install /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/nodemon/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.2.4 install /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/watchpack/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.1.3 install /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
In file included from     __attribute__((deprecated(message))) declarator../fsevents.cc
:6                   ^:

../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
In file included from ../fsevents.cc:6:
../../nan/nan.h:864NODE_DEPRECATED("Use MakeCallback(..., async_context)",:
18:^ 
warning: 'MakeCallback'/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h: 91is:20 :deprecated:  Use noteMakeCallback(...,:  async_context)expanded  [-Wdeprecated-declarations]from 
macro 'NODE_DEPRECATED'
    return node::MakeCallback(
                 ^
    __attribute__((deprecated(message))) declarator/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h
:162                   ^:
1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
In file included from     __attribute__((deprecated(message))) declarator../fsevents.cc
:6:
                   ^
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jinweizhang/.node-gyp/10.15.3/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1*** [Release/obj.target/fse/fsevents.o] Error 1

gypgyp  ERR!ERR!  build errorbuild error 
 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! gypstack      at ChildProcess.onExit (/Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gypERR!  ERR!stack  Error: `make` failed with exit code: 2
stack     at ChildProcess.emit (events.js:189:13)
gypgyp  ERR! ERR! stackstack     at ChildProcess.onExit (/Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gypgyp  ERR!ERR!  Systemcommand Darwin 18.2.0
 "/Users/jinweizhang/.nvm/versions/node/v10.15.3/bin/node" "/Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR!gyp cwd  /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents
ERR! gypcommand  "/Users/jinweizhang/.nvm/versions/node/v10.15.3/bin/node" "/Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
ERR! node -v v10.15.3
gyp gypERR!  ERR!cwd  /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents
node-gyp -v v3.8.0
gyp gypERR!  node -vERR! v10.15.3
 not ok 
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jinweizhang/.nvm/versions/node/v10.15.3/bin/node /Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/jinweizhang/.nvm/versions/node/v10.15.3/bin/node" "/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jinweizhang/.nvm/versions/node/v10.15.3/bin/node /Users/jinweizhang/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> node-sass@4.9.3 install /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/jinweizhang/.npm/node-sass/4.9.3/darwin-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.3 postinstall /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> nodemon@1.18.3 postinstall /Users/jinweizhang/Desktop/Project/try/lps-demo-web/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1692 packages from 885 contributors and audited 14323 packages in 23.041s
found 98 vulnerabilities (6 low, 70 moderate, 22 high)
  run `npm audit fix` to fix them, or `npm audit` for details
(base) jinweizhang@dyn3173-185:~/Desktop/Project/try/lps-demo-web$ npm start

> lps-demo-web@1.0.0 start /Users/jinweizhang/Desktop/Project/try/lps-demo-web
> npm run build && npm run server


> lps-demo-web@1.0.0 prebuild /Users/jinweizhang/Desktop/Project/try/lps-demo-web
> npm run clean


> lps-demo-web@1.0.0 clean /Users/jinweizhang/Desktop/Project/try/lps-demo-web
> rimraf dist


> lps-demo-web@1.0.0 build /Users/jinweizhang/Desktop/Project/try/lps-demo-web
> webpack


[at-loader] Using typescript@2.5.3 from typescript and "tsconfig.json" from /Users/jinweizhang/Desktop/Project/try/lps-demo-web/src/tsconfig.json.


[at-loader] Using typescript@2.5.3 from typescript and "tsconfig.json" from /Users/jinweizhang/Desktop/Project/try/lps-demo-web/src/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.422 sec.
DEPRECATION WARNING on line 3, column 8 of /Users/jinweizhang/Desktop/Project/try/lps-demo-web/src/assets/styles/main.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 3, column 8 of /Users/jinweizhang/Desktop/Project/try/lps-demo-web/src/assets/styles/main.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.401 sec.
Hash: 884a48714581595e2a4107df518ffe29d90da919
Version: webpack 3.12.0
Child
    Hash: 884a48714581595e2a41
    Time: 18140ms
                                                                         Asset       Size  Chunks                    Chunk Names
                                                           polyfills.client.js     927 kB       2  [emitted]  [big]  polyfills
      assets/glyphicons-halflings-regular.f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]         
     assets/glyphicons-halflings-regular.fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]         
      assets/glyphicons-halflings-regular.e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]         
      assets/glyphicons-halflings-regular.89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]         
               assets/fontawesome-webfont.674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
             assets/fontawesome-webfont.af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
              assets/fontawesome-webfont.fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
               assets/fontawesome-webfont.b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
               assets/fontawesome-webfont.912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
                                                              vendor.client.js    10.6 MB       0  [emitted]  [big]  vendor
                                                                 app.client.js    3.72 MB       1  [emitted]  [big]  app
    assets/glyphicons-halflings-regular.448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]         
                                                                       app.css     137 kB       1  [emitted]         app
                                                 assets/styles/_variables.scss   60 bytes          [emitted]         
                                                    assets/styles/buttons.scss  167 bytes          [emitted]         
                                                       assets/styles/form.scss  324 bytes          [emitted]         
                                                     assets/styles/common.scss  460 bytes          [emitted]         
                                                     assets/styles/footer.scss   74 bytes          [emitted]         
                                                       assets/styles/main.scss  219 bytes          [emitted]         
                                                   assets/styles/timeline.scss  715 bytes          [emitted]         
                                                    assets/styles/menubar.scss  802 bytes          [emitted]         
                                                                   favicon.ico    5.56 kB          [emitted]         
                                                                    index.html  786 bytes          [emitted]         
      [66] (webpack)/buildin/global.js 509 bytes {2} [built]
     [194] ./src/$$_gendir lazy 160 bytes {0} [built]
     [431] ./src/polyfills.ts 389 bytes {2} [built]
     [591] ./src/vendor.ts 432 bytes {0} [built]
     [887] ./src/main.ts 683 bytes {1} [built]
     [888] ./src/modules/app/browser-app.module.ts 1.6 kB {1} [built]
     [892] ./src/modules/app/app.module.ts 2.25 kB {1} [built]
     [893] ./src/modules/common/index.ts 300 bytes {1} [built]
     [894] ./src/modules/common/common.module.ts 1.87 kB {1} [built]
     [906] ./src/modules/app/pages/index.ts 296 bytes {1} [built]
     [909] ./src/modules/app/pages/about.page.ts 1.87 kB {1} [built]
     [911] ./src/modules/app/utility/index.ts 264 bytes {1} [built]
     [912] ./src/modules/app/utility/AnsiHtmlPipe.ts 1.63 kB {1} [built]
     [923] ./src/styles.scss 41 bytes {1} [built]
     [937] ./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/styles.scss 138 kB [built]
        + 932 hidden modules
    
    WARNING in EnvironmentPlugin - API_ENDPOINT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - NODE_ENV environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - PORT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    Child html-webpack-plugin for "index.html":
         1 asset
           [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.pug 523 bytes {0} [built]
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--6-2!node_modules/sass-loader/lib/loader.js!src/styles.scss:
         5 assets
           [1] ./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/styles.scss 138 kB {0} [built]
            + 7 hidden modules
Child
    Hash: 07df518ffe29d90da919
    Time: 12330ms
        Asset    Size  Chunks                    Chunk Names
    server.js  9.2 MB       0  [emitted]  [big]  main
      [15] ./src/$$_gendir lazy 160 bytes {0} [built]
      [37] ./src/main.server.ts 1.54 kB {0} [built]
      [42] ./src/modules/app/server-app.module.ts 1.72 kB {0} [built]
      [64] ./src/modules/app/app.module.ts 2.25 kB {0} [built]
      [65] ./src/modules/common/index.ts 300 bytes {0} [built]
      [66] ./src/modules/common/common.module.ts 1.87 kB {0} [built]
      [79] ./src/modules/app/pages/index.ts 296 bytes {0} [built]
      [80] ./src/modules/app/pages/home.page.ts 4.83 kB {0} [built]
      [81] ./src/modules/app/pages/home.page.pug 1.41 kB {0} [built]
      [82] ./src/modules/app/pages/about.page.ts 1.87 kB {0} [built]
      [83] ./src/modules/app/pages/about.page.pug 1.17 kB {0} [built]
      [84] ./src/modules/app/utility/index.ts 264 bytes {0} [built]
      [85] ./src/modules/app/utility/AnsiHtmlPipe.ts 1.63 kB {0} [built]
        + 80 hidden modules
    
    WARNING in EnvironmentPlugin - API_ENDPOINT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - NODE_ENV environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - PORT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.

> lps-demo-web@1.0.0 server /Users/jinweizhang/Desktop/Project/try/lps-demo-web
> nodemon dist/server.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: dist/*server.js
[nodemon] starting `node dist/server.js`
Listening at undefined

```
<img width="1423" alt="Screenshot 2019-04-19 at 10 15 28" src="https://user-images.githubusercontent.com/26280459/56417500-13e18100-628c-11e9-84fe-9001823270bb.png">

this is the index.html generated after running npm start.

I have attach the full command above:  
1. Basically I cloned the repo 
2. Then run npm i under node.js v10.15.3 (I have tried 8.11.3 and 6.0.0, both failed)
2. After that I tried to run npm start (the application build successfully but will not appear on http://localhost:3000/)

 I am not too sure which dependancy I should change, and I am new to node.js and webpack. Thank you in advanced.

Jinwei.

**Comment by mauris** [comment]
I noticed the issue. The output indicates the following:

````
    WARNING in EnvironmentPlugin - API_ENDPOINT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - NODE_ENV environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
    
    WARNING in EnvironmentPlugin - PORT environment variable is undefined.
    
    You can pass an object with default values to suppress this warning.
    See https://webpack.js.org/plugins/environment-plugin for example.
````

You need to define the following environment variables:

  - `API_ENDPOINT`: If I recall, this is the URL prefix to the [API web service](https://github.com/mauris/lps-demo-web-api) (e.g. `http://localhost:3000`)
  - `NODE_ENV`: this should be `development`, only set this to `production` when building for production
  - `PORT`: the local port to bind to, e.g. `8080`

---

For the gyp compilation failure I'm not so sure, it could be due to the gcc installed on your machine. See if it helps if you install an updated version of gcc using Homebrew.
